#define SHOUTVST_MAJOR_VERSION_INT   2
#define SHOUTVST_MAJOR_VERSION_STR   "2"

#define SHOUTVST_MINOR_VERSION_STR   "1"
#define SHOUTVST_MINOR_VERSION_INT   1

#define SHOUTVST_MAINT_VERSION_STR   "16"
#define SHOUTVST_MAINT_VERSION_INT   16



#define SHOUTVST_FULL_VERSION_STR   SHOUTVST_MAJOR_VERSION_STR "." SHOUTVST_MINOR_VERSION_STR "." SHOUTVST_MAINT_VERSION_STR
#define SHOUTVST_VERSION_INT         ((SHOUTVST_MAJOR_VERSION_INT*1000)+(SHOUTVST_MINOR_VERSION_INT*100)+SHOUTVST_MAINT_VERSION_INT)